image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package
    - cp target/don-quixote.jar .
  artifacts:
    paths:
      - don-quixote.jar
